package com.biscuit.soap.product.service.v1001;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.product.soap.biscuit.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ProductService {

    /**
     * 
     * @param arg0
     * @return returns
     *         java.util.List<com.biscuit.soap.product.service.ProductValuationDetails
     *         >
     * @throws ProductServiceFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductValuation", targetNamespace = "http://service.product.soap.biscuit.com/", className = "com.biscuit.soap.product.service.GetAllProductValuation")
    @ResponseWrapper(localName = "getAllProductValuationResponse", targetNamespace = "http://service.product.soap.biscuit.com/", className = "com.biscuit.soap.product.service.GetAllProductValuationResponse")
    public List<ProductValuationDetails> getAllProductValuation(
            @WebParam(name = "arg0", targetNamespace = "") ProductValue arg0) throws ProductServiceFault;

    /**
     * 
     * @param arg0
     * @return returns com.biscuit.soap.product.service.ProductDetails
     * @throws ProductServiceFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductDetailByProId", targetNamespace = "http://service.product.soap.biscuit.com/", className = "com.biscuit.soap.product.service.GetProductDetailByProId")
    @ResponseWrapper(localName = "getProductDetailByProIdResponse", targetNamespace = "http://service.product.soap.biscuit.com/", className = "com.biscuit.soap.product.service.GetProductDetailByProIdResponse")
    public ProductDetails getProductDetailByProId(@WebParam(name = "arg0", targetNamespace = "") ProductIdentity arg0)
            throws ProductServiceFault;

}
