package com.biscuit.soap.product.service.v1102;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "serviceFault", targetNamespace = "http://service.product.soap.biscuit.com/")
public class ProductServiceFault extends Exception {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProductServiceFault(String message, ServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProductServiceFault(String message, ServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return returns fault bean: com.biscuit.soap.product.service.ServiceFault
     */
    public ServiceFault getFaultInfo() {
        return faultInfo;
    }

}
